import type { IAllProps } from '@tinymce/tinymce-react'

type InitOptions = NonNullable<IAllProps['init']>

/** Font and size menus, generated by the website (scripts/fetch-fonts.ts) next to this plugin. */
export type EditorConfig = {
  fonts: { label: string; stack: string }[]
  sizes: { label: string; value: string }[]
  css: string
}

export const configUrl = new URL('../fonts/editor.json', window.location.href).toString()
let configPromise: Promise<EditorConfig> | null = null
export function loadConfig(): Promise<EditorConfig> {
  configPromise ??= fetch(configUrl, { cache: 'no-cache' }).then((r) => {
    if (!r.ok) throw new Error(`editor.json: HTTP ${r.status}`)
    return r.json()
  })
  return configPromise
}

/** Pasted text keeps bold/italic/links but not foreign fonts or sizes (from Word, Pages, websites). */
export function stripPastedTypography(node: HTMLElement) {
  node.querySelectorAll<HTMLElement>('[style]').forEach((el) => {
    el.style.removeProperty('font-family')
    el.style.removeProperty('font-size')
    if (!el.getAttribute('style')?.trim()) el.removeAttribute('style')
  })
  node.querySelectorAll('font').forEach((el) => el.replaceWith(...Array.from(el.childNodes)))
}

/** TinyMCE options shared by the DatoCMS field editor and the local harness. */
export function editorInit(config: EditorConfig, dark: boolean): InitOptions {
  const cssUrl = new URL(config.css, configUrl).toString()
  return {
    plugins: 'image advlist code link lists table autoresize',
    menubar: false,
    toolbar:
      'undo redo | blocks fontfamily fontsize | bold italic strikethrough | ' +
      'alignleft aligncenter alignright alignjustify | bullist numlist blockquote | ' +
      'link customimage table | removeformat code',
    toolbar_mode: 'wrap',
    font_family_formats: config.fonts.map((f) => `${f.label}=${f.stack}`).join('; '),
    font_size_formats: config.sizes.map((s) => `${s.label}=${s.value}`).join(' '),
    skin: dark ? 'oxide-dark' : 'oxide',
    content_css: dark ? 'dark' : 'default',
    // same fonts as the website; the site's own text is the browser default serif
    content_style: `@import url('${cssUrl}'); body { font-family: Times, 'Times New Roman', serif; font-size: 18px; }`,
    paste_postprocess: (_editor, args) => stripPastedTypography(args.node),
    autoresize_bottom_margin: 10,
    paste_data_images: true,
    promotion: false,
    branding: false,
  }
}
