/**
 * Self-hosts the enabled fonts (src/lib/fonts/catalog.ts): downloads the woff2 files from Google
 * once and writes
 *   public/fonts/<id>/*.woff2   the files (latin + latin-ext only)
 *   public/fonts/fonts.css      @font-face rules (browsers only download a font when text uses it)
 *   public/fonts/editor.json    Font/Size menus for the DatoCMS editor plugin
 *
 *   pnpm fonts:fetch
 *
 * Visitors never talk to Google (GDPR), and nothing here runs at request time.
 */
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { join } from 'node:path'
import { CATALOG, ENABLED, SIZE_STEPS, STANDARD, cssStack } from '../src/lib/fonts/catalog'

// a modern UA makes Google serve woff2 with unicode-range subsets
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36'
const KEEP = new Set(['latin', 'latin-ext'])
const OUT = 'public/fonts'

await rm(OUT, { recursive: true, force: true })
await mkdir(OUT, { recursive: true })

const css: string[] = ['/* Generated by scripts/fetch-fonts.ts, do not edit. */']
for (const id of ENABLED) {
  const f = CATALOG[id]
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(f.family).replace(/%20/g, '+')}:${f.axes}&display=swap`
  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`${f.family}: HTTP ${res.status} for ${url}`)
  const source = await res.text()
  await mkdir(join(OUT, id), { recursive: true })
  // blocks look like: /* latin */ @font-face { ... src: url(https://…woff2) format('woff2'); unicode-range: … }
  const blocks = [...source.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]+\})/g)]
  let kept = 0
  for (const [, subset, block] of blocks) {
    if (!KEEP.has(subset)) continue
    const remote = /url\((https:[^)]+\.woff2)\)/.exec(block)![1]
    const data = Buffer.from(await (await fetch(remote)).arrayBuffer())
    const name = `${createHash('sha1').update(data).digest('hex').slice(0, 10)}.woff2`
    await writeFile(join(OUT, id, name), data)
    css.push(`/* ${f.family} ${subset} */\n${block.replace(remote, `/fonts/${id}/${name}`)}`)
    kept++
  }
  if (!kept) throw new Error(`${f.family}: no latin subsets found`)
  console.log(`• ${f.family}: ${kept} files`)
}
await writeFile(join(OUT, 'fonts.css'), css.join('\n') + '\n')
await writeFile(
  join(OUT, 'editor.json'),
  JSON.stringify(
    {
      fonts: [STANDARD, ...ENABLED.map((id) => ({ label: CATALOG[id].family, stack: cssStack(CATALOG[id]) }))],
      sizes: SIZE_STEPS,
      css: '/fonts/fonts.css',
    },
    null,
    2
  ) + '\n'
)
console.log(`• wrote ${OUT}/fonts.css and editor.json`)
